# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_head', models.CharField(max_length=150)),
                ('post_text', models.CharField(max_length=10000)),
                ('post_date', models.DateTimeField(verbose_name='date published')),
                ('post_author', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=500)),
                ('comment_author', models.CharField(max_length=20)),
                ('comment_date', models.DateTimeField(verbose_name='comment date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.BlogPost')),
            ],
        ),
    ]
